server.port=8080
spring.application.name=talent-api

# Actuator — health endpoint
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=talent-api
info.app.description=Tech Chapter praktikant-udfordring
info.app.version=1.0.0
